name: Main

on: push

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:   [ubuntu-latest, macos-latest, windows-latest]
        node: [10, 12, 14]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with: { node-version: "${{ matrix.node }}" }
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint
