name: Settings

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: josa42/actions/update@main
        with:
          commit-message: "[auto] Update Settings"
          run-update: |
            npm update bash-language-server --save
            ./scripts/update-settings.mjs
          run-tests: |
            npm ci
            npm run build
            npm run lint
            npm run test
